name: cppcheck

on:
  push:
    branches:
      - master

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: flat_map.sarif
          category: cppcheck
